language: android
sudo: false
android:
  components:
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
before_install:
- cd replugin-plugin-library
- chmod +x gradlew
script:
- "./gradlew build bintrayUpload --info"
