language: android
sudo: false
android:
  components:
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
  
before_install:

script:
- cd replugin-host-library
- chmod +x gradlew
- "./gradlew build bintrayUpload --info"
- cd ../replugin-plugin-library
- chmod +x gradlew
- "./gradlew build bintrayUpload --info"
